### ISSUE TITLE
products KO

### ISSUE THREAD

**Issue by blondie63** [getcandy/demo-store#15]
Hi, i've installed this project following your guide without errors  
Project start but the product page fail with this msg:  
Illuminate\Database\QueryException  
SQLSTATE[42S22]: Column not found: 1054 Unknown column '__soft_deleted' in 'where clause' (SQL: select count(*) as aggregate from `getcandy_products` where __soft_deleted = %% AND (`getcandy_products`.`id` LIKE %% OR `getcandy_products`.`product_type_id` LIKE %% OR `getcandy_products`.`status` LIKE %% OR `getcandy_products`.`attribute_data` LIKE %% OR `getcandy_products`.`brand` LIKE %% OR `getcandy_products`.`created_at` LIKE %% OR `getcandy_products`.`updated_at` LIKE %% OR `getcandy_products`.`deleted_at` LIKE 0) and `getcandy_products`.`deleted_at` is null) (View: /Users/mauro/Documents/_projects/Laravel/demo-store/vendor/getcandy/admin/resources/views/livewire/pages/products/index.blade.php)
http://localhost:8000/hub/products

Some help ?

**Comment by glennjacobs** [comment]
That normally indicates that Meilsearch needs configuring. There is a known bug in the current release, hopefully solved when beta11 is released.

To solve you would run `php artisan getcandy:meilisearch:setup`
