### ISSUE TITLE
Faker locale must be `en_US` for order seeder to work

### ISSUE THREAD

**Issue by glennjacobs** [getcandy/demo-store#21]
How should we overcome this?

**Comment by alecritson** [comment]
I guess we'd set the locale to `en_US` in the config? Otherwise we'd need to write some sort of detection on the factory classes in GetCandy.

**Comment by glennjacobs** [comment]
But the config can get overwritten by the installer, I think?

**Comment by alecritson** [comment]
The faker locale is set by the Laravel config, not GetCandy so I don't think it would be?

**Comment by glennjacobs** [comment]
> The faker locale is set by the Laravel config, not GetCandy so I don't think it would be?

That's ok then.

**Comment by alecritson** [comment]
Looks like it's already set to `en_US` so should be able to close this.
