### ISSUE TITLE
Ability to bulk upload products from json, csv or xlsx file

### ISSUE THREAD

**Issue by rumensys** [getcandy/demo-store#33]
Do you plan to enable bulk products upload? It will be suitable for users who want to migrate from WordPress WooCommerce or some other platform. Existing database seeder can do some progress in that case, but JSON format is not user friendly to convert to or from XLSX file format.

**Comment by glennjacobs** [comment]
Certainly something we need to be considering I think. But not related to the demo store.

**Comment by glennjacobs** [comment]
I'm going to close this, as it's not relevant to the demo store and GetCandy does have an import/export addon planned.
