### ISSUE TITLE
Not Able To See Products && Not able to db:seed

### ISSUE THREAD

**Issue by workatfolium** [getcandy/demo-store#34]
hello,

i have installed this demo-store as per instructions , my project has setup completely. i served it using php artisan serve at http:127.0.0.1:8000. btw i am using laravel version  8.83.6.

but when i go to dashboard and try to open products the following error comes.

cURL error 7: Failed to connect to 127.0.0.1 port 7700: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://127.0.0.1:7700/indexes/demostore_products/search (View: C:\xampp\htdocs\demo-store\vendor\getcandy\admin\resources\views\livewire\pages\products\index.blade.php)

as well as when i try to seed data on command line using php artisan db:seed , the following error shows.

cURL error 7: Failed to connect to 127.0.0.1 port 7700: Connection refused (see h
ttps://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://127.0.0.1:7700/indexes/demostore_collections/documents?primaryKey=id

Any suggestion would greatly be appreciated.

thanks.

**Comment by glennjacobs** [comment]
It sounds very much like you do not have Meilisearch running correctly. You can change to use the database Laravel Scout driver instead if you wish.

**Comment by glennjacobs** [comment]
> actually i am using mysql database but that error comes often.

What Laravel Scout driver do you have configured?

**Comment by workatfolium** [comment]
meilisearch i didn;t configure it my own it came with it.

**Comment by glennjacobs** [comment]
No, you can just use the database, but the searching won't be as good. The demo store is configured to use Meilisearch as default.

See https://docs.getcandy.io/quickstart.html

Try setting `SCOUT_DRIVER=mysql` in your `.env` file.

**Comment by workatfolium** [comment]
> 
After Doing (SCOUT_DRIVER=mysql) and run (php artisan db:seed ) the following error came out.

```
 
   Error

  Class "Yab\MySQLScout\Engines\Modes\" not found

  at C:\xampp\htdocs\getcandy\vendor\yab\laravel-scout-mysql-driver\src\Providers\MySQLScoutServiceProvider.php:50
     46▕             $engineNamespace = 'Yab\\MySQLScout\\Engines\\Modes\\';
     47▕             $mode = $engineNamespace.Str::studly(strtolower(config('scout.mysql.mode')));
     48▕             $fallbackMode = $engineNamespace.Str::studly(strtolower(config('scout.mysql.min_fulltext_search_fallback')));
     49▕
  ➜  50▕             return new ModeContainer(new $mode(), new $fallbackMode());
     51▕         });
     52▕     }
     53▕ }
     54▕

  1   C:\xampp\htdocs\getcandy\vendor\laravel\framework\src\Illuminate\Container\Container.php:873
      Yab\MySQLScout\Providers\MySQLScoutServiceProvider::Yab\MySQLScout\Providers\{closure}(Object(Illuminate\Foundation\Application), [])

  2   C:\xampp\htdocs\getcandy\vendor\laravel\framework\src\Illuminate\Container\Container.php:758
      Illuminate\Container\Container::build(Object(Closure))
```
