### ISSUE TITLE
how to download the version for php 8.0?

### ISSUE THREAD

**Issue by fatklass** [getcandy/demo-store#37]
how to download the release for php 8.0?

`
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/dbal 3.3.7 -> satisfiable by doctrine/dbal[3.3.7].
    - doctrine/dbal 3.3.7 requires composer-runtime-api ^2 -> no matching package found.
  Problem 2
    - Installation request for symfony/deprecation-contracts v3.1.0 -> satisfiable by symfony/deprecation-contracts[v3.1.0].
    - symfony/deprecation-contracts v3.1.0 requires php >=8.1 -> your PHP version (8.0.8) does not satisfy that requirement.
  Problem 3
    - Installation request for symfony/event-dispatcher v6.1.0 -> satisfiable by symfony/event-dispatcher[v6.1.0].
    - symfony/event-dispatcher v6.1.0 requires php >=8.1 -> your PHP version (8.0.8) does not satisfy that requirement.
  Problem 4
    - Installation request for symfony/event-dispatcher-contracts v3.1.0 -> satisfiable by symfony/event-dispatcher-contracts[v3.1.0].
    - symfony/event-dispatcher-contracts v3.1.0 requires php >=8.1 -> your PHP version (8.0.8) does not satisfy that requirement.
  Problem 5
    - Installation request for symfony/options-resolver v6.1.0 -> satisfiable by symfony/options-resolver[v6.1.0].
    - symfony/options-resolver v6.1.0 requires php >=8.1 -> your PHP version (8.0.8) does not satisfy that requirement.
  Problem 6
    - Installation request for symfony/string v6.1.2 -> satisfiable by symfony/string[v6.1.2].
    - symfony/string v6.1.2 requires php >=8.1 -> your PHP version (8.0.8) does not satisfy that requirement.
  Problem 7
    - Installation request for symfony/translation-contracts v3.1.0 -> satisfiable by symfony/translation-contracts[v3.1.0].
    - symfony/translation-contracts v3.1.0 requires php >=8.1 -> your PHP version (8.0.8) does not satisfy that requirement.
  Problem 8
    - symfony/deprecation-contracts v3.1.0 requires php >=8.1 -> your PHP version (8.0.8) does not satisfy that requirement.
    - fakerphp/faker v1.19.0 requires symfony/deprecation-contracts ^2.2 || ^3.0 -> satisfiable by symfony/deprecation-contracts[v3.1.0].
    - Installation request for fakerphp/faker v1.19.0 -> satisfiable by fakerphp/faker[v1.19.0].

Potential causes:
 - This package is not installable via Composer 1.x, see <https://blog.packagist.com/deprecating-composer-1-support/>
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
`

**Comment by alecritson** [comment]
You could try removing the composer.lock and vendor directory and installing

**Comment by fatklass** [comment]
@alecritson Thanks, this solved the installation problem.

_There was also a problem with ErrorNumberFormatter
Error
Class "NumberFormatter" not found (View: D:\srv\os\domains\newbora\vendor\getcandy\admin\resources\views\livewire\dashboard.blade.php)_

Solved by enabling the php component
extension=intl

**Comment by andrewdrake** [comment]
Just run `composer update` instead of `composer install`
